baseURL = "https://blog.phundrak.com/"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
title = "Phundrak’s rambling"
theme = "m10c"
paginate = 10
enableInlineShortcodes = true
staticDir = ["static"]

summarylength = 10
enableEmoji = true

[author]
  name = "Lucien Cartier-Tilet"

[params]
  author = "Lucien Cartier-Tilet"
  description = "Some random rambling by a linguistics nerd about Emacs, Linux, and conlanging"
  avatar = "leon.png"

  [[params.social]]
    name = "github"
    url = "https://github.com/phundrak"

  [[params.social]]
    name = "git-merge"
    url = "https://labs.phundrak.com/phundrak"

  [[params.social]]
    name = "lind-2"
    url = "https://phundrak.com"

  [[params.social]]
    name = "flag"
    url = "https://conlang.phundrak.com"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/phundrak"

  [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/@phundrak"

  [[params.social]]
    name = "mail"
    url = "mailto:lucien@phundrak.com"

  [[params.social]]
    name = "rss"
    url = "https://blog.phundrak.com/index.xml"

  [params.style]
   darkestColor = "#2e3440"
   darkColor = "#4c566a"
   primaryColor = "#8fbcbb"
   lightColor = "#d8dee9"
   lightestColor = "#eceff4"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true